var foods = [
    {
        "id": 1,
        "name": "Apple",
        "image": "https://i.ibb.co/vPJPFvk/apple.jpg",
        "calories": 52,
        "fat": 0.2,
        "cholesterol": 0,
        "carbohydrate": 14,
        "description": "It contains vitamin: A, B-6, C, D", 
    },
    {
        "id": 2,
        "name": "Orange",
        "image": "https://i.ibb.co/P5kMfdC/orange.jpg",
        "calories": 47,
        "fat": 0.1,
        "cholesterol": 0,
        "carbohydrate": 12,
        "description": "It contains vitamin: A, B-6, C, D",
    },
    {
        "id": 3,
        "name": "Banana",
        "image": "https://i.ibb.co/0j8yQJh/banana.jpg",
        "calories": 89,
        "fat": 0.3,
        "cholesterol": 0,
        "carbohydrate": 23,
        "description": "It contains vitamin: A, B-6, C, D",
    },
    {
        "id": 4,
        "name": "Blueberry",
        "image": "https://i.ibb.co/nz2WNFh/blueberry.jpg",
        "calories": 57,
        "fat": 0.3,
        "cholesterol": 0,
        "carbohydrate": 14,
        "description": "It contains vitamin: A, B-6, C, D",
    },
    {
        "id": 5,
        "name": "Avocado",
        "image": "https://i.ibb.co/DQ3brQW/avocado.jpg",
        "calories": 160,
        "fat": 15,
        "cholesterol": 0,
        "carbohydrate": 9,
        "description": "It contains vitamin: A, B-6, C, D",
    },
    {
        "id": 6,
        "name": "Cherries",
        "image": "https://i.ibb.co/x1mjzS2/cherries.jpg",
        "calories": 50,
        "fat": 0.3,
        "cholesterol": 0,
        "carbohydrate": 12,
        "description": "It contains vitamin: A, B-6, C, D",
    },
    {
        "id": 7,
        "name": "Guava",
        "image": "https://i.ibb.co/MDkTFwz/guava.jpg",
        "calories": 68,
        "fat": 1,
        "cholesterol": 0,
        "carbohydrate": 14,
        "description": "It contains vitamin: A, B-6, C, D",
    },

]

export default foods;